# Generated by Django 4.2.30 on 2026-06-21 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClipJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_url", models.URLField(max_length=2048)),
                ("video_id", models.CharField(blank=True, max_length=64)),
                (
                    "video_title",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("n_clips", models.PositiveSmallIntegerField(default=5)),
                (
                    "max_duration",
                    models.PositiveSmallIntegerField(
                        default=60, help_text="Maximum clip duration in seconds"
                    ),
                ),
                (
                    "custom_focus",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Optional focus area for the AI (e.g. "funny moments", "key insights")',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clip_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip Job",
                "verbose_name_plural": "Clip Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClipSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("start_time", models.FloatField(help_text="Start time in seconds")),
                ("end_time", models.FloatField(help_text="End time in seconds")),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="The rendered clip video file",
                        upload_to="clips/",
                    ),
                ),
                ("is_downloaded", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clips",
                        to="yt_tools.clipjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip Segment",
                "verbose_name_plural": "Clip Segments",
                "ordering": ["start_time"],
            },
        ),
    ]
