# Generated by Django 4.2.30 on 2026-06-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yt_tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clipjob",
            name="progress_step",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable current step for the UI",
                max_length=128,
            ),
        ),
    ]
