from django.conf import settings
from django.db import models


class ClipJob(models.Model):
    """Tracks a single clip-generation request."""

    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        PROCESSING = 'processing', 'Processing'
        DONE = 'done', 'Done'
        ERROR = 'error', 'Error'

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='clip_jobs',
    )
    youtube_url = models.URLField(max_length=2048)
    video_id = models.CharField(max_length=64, blank=True)
    video_title = models.CharField(max_length=512, blank=True, default='')
    n_clips = models.PositiveSmallIntegerField(default=5)
    max_duration = models.PositiveSmallIntegerField(
        default=60, help_text='Maximum clip duration in seconds'
    )
    custom_focus = models.TextField(
        blank=True, default='',
        help_text='Optional focus area for the AI (e.g. "funny moments", "key insights")',
    )
    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.PENDING,
    )
    progress_step = models.CharField(
        max_length=128, blank=True, default='',
        help_text='Human-readable current step for the UI',
    )
    error_message = models.TextField(blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Clip Job'
        verbose_name_plural = 'Clip Jobs'

    @property
    def progress_pct(self) -> int:
        """Parse the percentage from progress_step (format: ``"20%|Fetching..."``)."""
        if '|' not in self.progress_step:
            return 0
        try:
            return int(self.progress_step.split('|')[0].rstrip('% '))
        except (ValueError, IndexError):
            return 0

    @property
    def progress_label(self) -> str:
        """Parse the label from progress_step."""
        if '|' not in self.progress_step:
            return self.progress_step or 'Starting...'
        return self.progress_step.split('|', 1)[1]

    def __str__(self):
        return f'{self.video_title or self.video_id or self.youtube_url} ({self.status})'


class ClipSegment(models.Model):
    """An individual clip segment generated by AI."""

    job = models.ForeignKey(
        ClipJob,
        on_delete=models.CASCADE,
        related_name='clips',
    )
    title = models.CharField(max_length=256)
    start_time = models.FloatField(help_text='Start time in seconds')
    end_time = models.FloatField(help_text='End time in seconds')
    reason = models.TextField(blank=True, default='')
    video_file = models.FileField(
        upload_to='clips/',
        blank=True,
        help_text='The rendered clip video file',
    )
    is_downloaded = models.BooleanField(default=False)

    class Meta:
        ordering = ['start_time']
        verbose_name = 'Clip Segment'
        verbose_name_plural = 'Clip Segments'

    def __str__(self):
        return f'{self.title} ({self.start_time}s - {self.end_time}s)'

    @property
    def duration(self):
        return round(self.end_time - self.start_time, 1)
